sudo: false
language: node_js
node_js:
  - 8
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - "npm run build"
  - "npm run build-storybook"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/
  on:
    branch: master
