/* eslint-disable import/prefer-default-export */

export const UNAUTH = 'UNAUTH';
export const AUTH_FETCH = 'AUTH_FETCH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const INVOICES_FETCH = 'INVOICES_FETCH';
export const INVOICES_FETCH_SUCCESS = 'INVOICES_FETCH_SUCCESS';
export const ONE_INVOICE_FETCH = 'ONE_INVOICE_FETCH';
export const ONE_INVOICE_FETCH_SUCCESS = 'ONE_INVOICE_FETCH_SUCCESS';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const UPDATE_LAST_INVOICE_ID = 'UPDATE_LAST_INVOICE_ID';
